---
title: "CSGlossary"
author: "Beth Davis"
repository: "livingcode records"
date_created: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Databases
SQL - Structured Query Language
Database - A collection of data stored in an easily accessible format
Non-Relational Databases (NoSQL) - a database that doesn't understand SQL since they don't utilize tables or relationships
Relational Database (RDBMS) - Data is stored in tables linked to each other by relationships. Each data stores a specific type of data, and SQL is used to query the data based on columns. This improves search sensitivity and protects data from accidental changes

MySQl, SQL Server, Oracle are popular RDBMS
Querying - gets specific data out of a database
Procedural - goes row-by-row
Set-based - returns the specific set you want
Types - Fields are sorted into types based on what information they contain and only one type can be assigned to each field or column
CHAR/CHARACTER- character string, must assign a fixed length ()
VARCHAR or CHARACTER VARYING - character string of variable length, must set a max length
Binary - binary string with fixed length
Boolean - True/False
VARBINARY or BINARY VARYING - binary string of variable length, must set fixed length
INTEGER - integer
SMALLINT - integer
BIGINT - integer
DECIMAL(p,s) - exact number with precision p and scale s
Number (p,s) - same as DECIMAL
Float(p) - approx number with precision p
REAL - approx number
FLOAT - approx number
DOUBLE PRECISION - approx number
DATE - date in YYYY/MM/DD format
TIME - time in hour, min, sec
TIMESTAMP - ^ date and time together
INTERVAL - composed of a number of integer fields representing a time period
ARRAY - a set-length and ordered collection of elements
MULTISET - a variable-length and unordered collection of elements
XML - stores XML data